export const TAILWIND_UTILITIES = [
	/* ======================================== */
	/* Colors */
	/* ======================================== */
	'bg-primary',
	'bg-secondary',
	'bg-tertiary',
	'bg-quaternary',

	/* ======================================== */
	/* Fonts */
	/* ======================================== */
	// Fonts - Colors
	'text-inherit',
	'text-current',
	'text-transparent',
	'text-primary',
	'text-secondary',
	'text-tertiary',
	'text-quaternary',
	'text-black',
	'text-white',
	// Fonts - Alignment
	'text-left',
	'text-right',
	'text-center',
	'text-justify',
	'text-start',
	'text-end',
	// Fonts - Family
	'font-heading',
	'font-body',
	// Fonts - Size
	'text-xs',
	'text-sm',
	'text-base',
	'text-lg',
	'text-xl',
	'text-2xl',
	'text-3xl',
	'text-4xl',
	'text-5xl',
	'text-6xl',
	// Fonts - Smoothing
	'antialiased',
	'subpixel-antialiased',
	// Fonts - Style
	'italic',
	'not-italic',
	// Fonts - Weight
	'font-thin',
	'font-extralight',
	'font-light',
	'font-normal',
	'font-medium',
	'font-semibold',
	'font-bold',
	'font-extrabold',
	'font-black',

	/* ======================================== */
	/* Margins */
	/* ======================================== */
	// Margins - All
	'm-10',
	'm-20',
	'm-30',
	'm-40',
	'm-50',
	'm-60',
	'm-70',
	'm-80',
	// Margins - Horizontal
	'mx-auto',
	'mx-10',
	'mx-20',
	'mx-30',
	'mx-40',
	'mx-50',
	'mx-60',
	'mx-70',
	'mx-80',
	// Margins - Vertical
	'my-auto',
	'my-10',
	'my-20',
	'my-30',
	'my-40',
	'my-50',
	'my-60',
	'my-70',
	'my-80',
	// Margins - Top
	'mt-10',
	'mt-20',
	'mt-30',
	'mt-40',
	'mt-50',
	'mt-60',
	'mt-70',
	'mt-80',
	// Margins - Bottom
	'mb-10',
	'mb-20',
	'mb-30',
	'mb-40',
	'mb-50',
	'mb-60',
	'mb-70',
	'mb-80',
	// Margins - Left
	'ml-10',
	'ml-20',
	'ml-30',
	'ml-40',
	'ml-50',
	'ml-60',
	'ml-70',
	'ml-80',
	// Margins - Right
	'mr-10',
	'mr-20',
	'mr-30',
	'mr-40',
	'mr-50',
	'mr-60',
	'mr-70',
	'mr-80',

	/* ======================================== */
	/* Paddings */
	/* ======================================== */
	'p-10',
	'p-20',
	'p-30',
	'p-40',
	'p-50',
	'p-60',
	'p-70',
	'p-80',
	// Paddings - Horizontal
	'px-auto',
	'px-10',
	'px-20',
	'px-30',
	'px-40',
	'px-50',
	'px-60',
	'px-70',
	'px-80',
	// Paddings - Vertical
	'py-auto',
	'py-10',
	'py-20',
	'py-30',
	'py-40',
	'py-50',
	'py-60',
	'py-70',
	'py-80',
	// Paddings - Top
	'pt-10',
	'pt-20',
	'pt-30',
	'pt-40',
	'pt-50',
	'pt-60',
	'pt-70',
	'pt-80',
	// Paddings - Bottom
	'pb-10',
	'pb-20',
	'pb-30',
	'pb-40',
	'pb-50',
	'pb-60',
	'pb-70',
	'pb-80',
	// Paddings - Left
	'pl-10',
	'pl-20',
	'pl-30',
	'pl-40',
	'pl-50',
	'pl-60',
	'pl-70',
	'pl-80',
	'pr-10',
	'pr-20',
	'pr-30',
	'pr-40',
	'pr-50',
	'pr-60',
	'pr-70',
	'pr-80',

	/* ======================================== */
	/* Grid & Flex */
	/* ======================================== */
	'grid',
	'flex',
	// Columns
	'grid-cols-none',
	'grid-cols-1',
	'grid-cols-2',
	'grid-cols-3',
	'grid-cols-4',
	'grid-cols-5',
	'grid-cols-6',
	// Rows
	'grid-rows-none',
	'grid-rows-1',
	'grid-rows-2',
	'grid-rows-3',
	'grid-rows-4',
	'grid-rows-5',
	'grid-rows-6',
	// Subgrid
	'grid-cols-subgrid',
	// Order
	'order-none',
	'order-first',
	'order-last',
	'order-1',
	'order-2',
	'order-3',
	'order-4',
	'order-5',
	'order-6',
	// Gap
	'gap-1',
	'gap-2',
	'gap-3',
	'gap-4',
	'gap-5',
	'gap-6',
	'gap-7',
	'gap-8',
	// Gap - Row
	'gap-x-1',
	'gap-x-2',
	'gap-x-3',
	'gap-x-4',
	'gap-x-5',
	'gap-x-6',
	'gap-x-7',
	'gap-x-8',
	// Gap - Column
	'gap-y-1',
	'gap-y-2',
	'gap-y-3',
	'gap-y-4',
	'gap-y-5',
	'gap-y-6',
	'gap-y-7',
	'gap-y-8',
	// Justify
	'justify-start',
	'justify-end',
	'justify-center',
	'justify-between',
	'justify-around',
	'justify-evenly',
	'justify-stretch',
	'justify-baseline',
	'justify-normal',
	'justify-items-start',
	'justify-items-end',
	'justify-items-center',
	'justify-items-stretch',
	'justify-items-normal',
	'justify-self-auto',
	'justify-self-start',
	'justify-self-end',
	'justify-self-center',
	'justify-self-stretch',
	// Align
	'content-normal',
	'content-center',
	'content-start',
	'content-end',
	'content-between',
	'content-around',
	'content-evenly',
	'content-baseline',
	'content-stretch',
	'items-start',
	'items-end',
	'items-center',
	'items-baseline',
	'items-stretch',
	'self-auto',
	'self-start',
	'self-end',
	'self-center',
	'self-stretch',
	'self-baseline',
	// Place
	'place-content-center',
	'place-content-start',
	'place-content-end',
	'place-content-between',
	'place-content-around',
	'place-content-evenly',
	'place-content-stretch',
	'place-content-baseline',
	'place-items-start',
	'place-items-end',
	'place-items-center',
	'place-items-stretch',
	'place-items-baseline',
	'place-self-auto',
	'place-self-start',
	'place-self-end',
	'place-self-center',
	'place-self-stretch',
];
