/**
 * Vite 6 enhanced manifest utilities for WordPress
 */

import { WORDPRESS_EXTERNALS } from '../constants.js';

interface ViteManifestChunk {
	file: string;
	css?: string[];
	imports?: string[];
	assets?: string[];
	isEntry?: boolean;
	src?: string;
}

interface ViteManifest {
	[key: string]: ViteManifestChunk;
}

interface WordPressAssetManifest {
	[key: string]: {
		file: string;
		css: string[];
		dependencies: string[];
		version: string;
		in_footer: boolean;
	};
}

/**
 * Convert Vite 6 manifest to WordPress-compatible format
 * Leverages improved manifest structure in Vite 6
 */
export function convertViteManifestToWordPress(
	viteManifest: ViteManifest,
	publicPath: string = '/'
): WordPressAssetManifest {
	const wpManifest: WordPressAssetManifest = {};

	for (const [_src, chunk] of Object.entries(viteManifest)) {
		// Only process entry chunks for WordPress
		if (chunk.isEntry && chunk.src) {
			const assetKey = chunk.src.replace(/\.(ts|js|tsx|jsx)$/, '');

			wpManifest[assetKey] = {
				file: `${publicPath}${chunk.file}`,
				css: (chunk.css || []).map((css) => `${publicPath}${css}`),
				dependencies: extractWordPressDependencies(chunk),
				version: generateVersionFromFile(chunk.file),
				in_footer: shouldLoadInFooter(chunk.src),
			};
		}
	}

	return wpManifest;
}

/**
 * Extract WordPress dependencies from chunk imports
 * Uses Vite 6's improved dependency tracking
 */
function extractWordPressDependencies(chunk: ViteManifestChunk): string[] {
	const dependencies = new Set<string>();

	// Use modern WordPress externals from constants
	const wpCoreDeps = Object.fromEntries(
		Object.keys(WORDPRESS_EXTERNALS)
			.filter((key) => key.startsWith('@wordpress/'))
			.map((key) => [key, key.replace('@wordpress/', 'wp-')])
	);

	// Add common mappings
	wpCoreDeps.react = 'wp-element';
	wpCoreDeps['react-dom'] = 'wp-element';

	// Process imports to find WordPress dependencies
	if (chunk.imports) {
		chunk.imports.forEach((importPath) => {
			for (const [jsModule, wpDep] of Object.entries(wpCoreDeps)) {
				if (importPath.includes(jsModule)) {
					dependencies.add(wpDep);
				}
			}
		});
	}

	return Array.from(dependencies);
}

/**
 * Generate version hash from filename
 * Improved with Vite 6's better file hashing
 */
function generateVersionFromFile(filename: string): string {
	const match = filename.match(/[.-]([a-f0-9]{8,})\./);
	return match ? match[1].substring(0, 8) : '1.0.0';
}

/**
 * Determine if script should load in footer
 * Enhanced logic for WordPress context
 */
function shouldLoadInFooter(src: string): boolean {
	// Admin scripts typically load in head
	if (src.includes('admin')) return false;

	// Theme scripts load in footer by default
	if (src.includes('theme') || src.includes('frontend')) return true;

	// Default to footer for better performance
	return true;
}

/**
 * Generate WordPress PHP enqueue file from manifest
 * Leverages Vite 6's manifest improvements
 */
export function generateWordPressEnqueueFile(
	wpManifest: WordPressAssetManifest,
	_textDomain: string = 'theme'
): string {
	const lines = [
		'<?php',
		'/**',
		' * Auto-generated asset manifest for WordPress',
		' * Generated by Vite 6 WordPress plugin',
		' */',
		'',
		"if (!defined('ABSPATH')) {",
		'    exit;',
		'}',
		'',
		'return [',
	];

	for (const [handle, asset] of Object.entries(wpManifest)) {
		lines.push(`    '${handle}' => [`);
		lines.push(`        'file' => '${asset.file}',`);
		lines.push(
			`        'dependencies' => [${asset.dependencies.map((dep) => `'${dep}'`).join(', ')}],`
		);
		lines.push(`        'version' => '${asset.version}',`);
		lines.push(
			`        'in_footer' => ${asset.in_footer ? 'true' : 'false'},`
		);

		if (asset.css.length > 0) {
			lines.push(
				`        'css' => [${asset.css.map((css) => `'${css}'`).join(', ')}],`
			);
		}

		lines.push('    ],');
	}

	lines.push('];');

	return lines.join('\n');
}
