/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';
import apiFetch from '@wordpress/api-fetch';

/**
 * Internal dependencies
 */
import { OptionBody, OptionGroup, Option } from '@admin/containers';
import { Button } from '@admin/misc';

/**
 * General Settings Page
 * @return {JSX.Element} JSX for the general settings page
 */
const General = (): JSX.Element => {
	const { nonce } = window.kotisivuSettings as KotisivuSettings;

	/**
	 * Handle clearing the cache
	 * @return {void}
	 */
	const handleClearCache = (): void => {
		apiFetch.use(apiFetch.createNonceMiddleware(nonce));

		apiFetch({
			method: 'POST',
			path: 'kotisivu-block-theme/v1/options/purge-cache',
			data: {},
		}).then(() => {
			// eslint-disable-next-line no-alert
			window.alert(
				__('Transients have been cleared.', 'kotisivu-block-theme')
			);
		});
	};

	return (
		<OptionBody name={__('General Settings', 'kotisivu-block-theme')}>
			<OptionGroup>
				<Option
					name={__('Cache', 'kotisivu-block-theme')}
					description={__(
						'Clear theme generated transients here. Please note that this does not handle transients or cache that is generated by other plugins.',
						'kotisivu-block-theme'
					)}
				>
					<Button
						name={__('Clear Cache', 'kotisivu-block-theme')}
						onClick={handleClearCache}
					/>
				</Option>
			</OptionGroup>
		</OptionBody>
	);
};

export default General;
