/**
 * Internal dependencies
 */
import type { WordPressAssetManifest } from '../../types.js';

/**
 * Generate a PHP file for WordPress enqueueing assets
 * This function creates a PHP array that can be used in WordPress
 * to enqueue scripts and styles based on the provided manifest.
 *
 * @param wpManifest - The WordPress asset manifest.
 * @param textDomain - The text domain for localization, defaults to 'theme'.
 * @return A string containing the PHP code for the asset manifest.
 */
export function generateWordPressEnqueueFile(
	wpManifest: WordPressAssetManifest,
	_textDomain: string = 'theme'
): string {
	const lines = [
		'<?php',
		'/**',
		' * Auto-generated asset manifest for WordPress',
		' * Generated by Vite 6 WordPress plugin',
		' */',
		'',
		"if (!defined('ABSPATH')) {",
		'    exit;',
		'}',
		'',
		'return [',
	];

	for (const [handle, asset] of Object.entries(wpManifest)) {
		lines.push(`    '${handle}' => [`);
		lines.push(`        'file' => '${asset.file}',`);
		lines.push(
			`        'dependencies' => [${asset.dependencies.map((dep) => `'${dep}'`).join(', ')}],`
		);
		lines.push(`        'version' => '${asset.version}',`);
		lines.push(
			`        'in_footer' => ${asset.in_footer ? 'true' : 'false'},`
		);

		if (asset.css.length > 0) {
			lines.push(
				`        'css' => [${asset.css.map((css) => `'${css}'`).join(', ')}],`
			);
		}

		lines.push('    ],');
	}

	lines.push('];');

	return lines.join('\n');
}
