name: JS

on: [pull_request]

jobs:
    lint-js:
        name: JS
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: yarn
            - name: Build and run linting
              run: |
                  yarn build
                  yarn lint:js
